1.
Write a function to compute 5/0 and use try/except to catch the exceptions.


In [1]:
def divide(a,b):
    
    try:
        c=a/b
        return c
    except Exception as e:
        print(e,type(e))
        
def main():
    try:
        a=int(input("Enter a:"))
        b=int(input("Enter b:"))
        c=divide(a,b)
        print(c)
    except Exception as e:
        print(e,type(e))
        
if __name__ == '__main__':
    main()

Enter a:5
Enter b:0
division by zero <class 'ZeroDivisionError'>
None


2.
Implement a Python program to generate all sentences where subject is in ["Americans",

"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

Hint: Subject,Verb and Object should be declared in the program as shown below.

subjects=["Americans ","Indians"]

verbs=["play","watch"]

objects=["Baseball","Cricket"]

Output should come as below:

Americans play Baseball.

Americans play Cricket.

Americans watch Baseball.

Americans watch Cricket.

Indians play Baseball.

Indians play Cricket.

Indians watch Baseball.

Indians watch Cricket.

In [2]:
subjects=["Americans ","Indians"]

verbs=["play","watch"]

objects=["Baseball","Cricket"]

for sub in subjects:
    for verb in verbs:
        for obj in objects:
            print( sub +" "+verb+" "+obj)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


## Task 2:
1.
Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [4]:
import numpy as np
def OutputMatrix(I,N,bool=False):
    out=[]
    if bool==True:
        for j in range(N):
            out.append([(v**j)for v in I])
                
    else:
        for j in range(N-1,-1,-1):
            out.append([(v**j)for v in I])
                
    out_matrix = np.array(out)
    out_matrix=np.transpose(out_matrix)
             
    return out_matrix
def main():
    
    try:
        l=[]
        n=int(input("Enter the array size:"))
        for i in range(n):
            l.append(int(input("Enter the {} element :".format(i))))
        Input=np.array(l)
        if Input.ndim!=1:
                raise ValueError("Input must be a one-dimensional array or sequence.")
        
    except Exception as e:
        print(e,type(e))
    try:
        N=int(input('Enter the no of columns of output matrix:'))
        if N==None:
                N=len(Input)
    except Exception as e:
            print(e,type(e))
    
    print(OutputMatrix(Input,N,True))
    
    
if __name__ == '__main__':
    main()
    

    

    
        
        
    

Enter the array size:4
Enter the 0 element :1
Enter the 1 element :2
Enter the 2 element :3
Enter the 3 element :4
Enter the no of columns of output matrix:5
[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]]
